# Generated by Django 3.1.2 on 2020-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201110_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.CharField(default='time', max_length=30),
        ),
    ]
