# Generated by Django 3.1.2 on 2020-11-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-11 03:15:31', max_length=30),
        ),
    ]
