# Generated by Django 3.1.2 on 2020-11-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201115_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder',
        ),
        migrations.AddField(
            model_name='bid',
            name='username',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_comments', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_watch', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='username',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-17 00:51:09', max_length=30),
        ),
    ]
