# Generated by Django 3.1.2 on 2020-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201117_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-17 06:36:27', max_length=30),
        ),
    ]
