# Generated by Django 3.1.2 on 2020-11-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201117_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-22 18:24:44', max_length=30),
        ),
    ]
