# Generated by Django 3.1.2 on 2020-11-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201123_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-24 00:21:19', max_length=30),
        ),
    ]
