# Generated by Django 3.1.2 on 2020-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201124_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.CharField(default='2020-11-29 23:39:36', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.CharField(default='2020-11-29 23:39:36', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='2020-11-29 23:39:36', max_length=30),
        ),
    ]
