# Generated by Django 3.1.2 on 2020-12-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201129_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
